export enum AuthConstants {
    TOKEN = 'TOKEN_POKEMON',
    REFRESH_TOKEN = 'REFRESH_TOKEN_POKEMON',
    USER_INFO = 'USER_INFO_POKEMON',
    PERMISSION = 'PERMISSION_POKEMON',
    MENUS = 'MENU_POKEMON',
}
